apiVersion: v1
kind: PersistentVolume
metadata:
  name: details-pv-volume
  namespace : demo-tinfo
  labels:
    type: local
spec:
  storageClassName: details-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/demo-tinfo/details"
