apiVersion: v1
kind: Service
metadata:
  name: springboot-details-service
  namespace: demo-tinfo
  labels:
    app: springboot-details
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 32295
    protocol: TCP
    name: http
  selector:
    app: springboot-details
